#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL_DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLDVXeKhach")]
	public partial class QLDVXeKhachDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChuyenXe(ChuyenXe instance);
    partial void UpdateChuyenXe(ChuyenXe instance);
    partial void DeleteChuyenXe(ChuyenXe instance);
    partial void InsertDiaDiem(DiaDiem instance);
    partial void UpdateDiaDiem(DiaDiem instance);
    partial void DeleteDiaDiem(DiaDiem instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertVeXe(VeXe instance);
    partial void UpdateVeXe(VeXe instance);
    partial void DeleteVeXe(VeXe instance);
    partial void InsertXe(Xe instance);
    partial void UpdateXe(Xe instance);
    partial void DeleteXe(Xe instance);
    #endregion
		
		public QLDVXeKhachDataContext() : 
				base(global::BLL_DAL.Properties.Settings.Default.QLDVXeKhachConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLDVXeKhachDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDVXeKhachDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDVXeKhachDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDVXeKhachDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChuyenXe> ChuyenXes
		{
			get
			{
				return this.GetTable<ChuyenXe>();
			}
		}
		
		public System.Data.Linq.Table<DiaDiem> DiaDiems
		{
			get
			{
				return this.GetTable<DiaDiem>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<VeXe> VeXes
		{
			get
			{
				return this.GetTable<VeXe>();
			}
		}
		
		public System.Data.Linq.Table<Xe> Xes
		{
			get
			{
				return this.GetTable<Xe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChuyenXe")]
	public partial class ChuyenXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCX;
		
		private string _DiemDi;
		
		private string _DiemDen;
		
		private System.Nullable<System.DateTime> _NgayDi;
		
		private System.Nullable<decimal> _GiaVe;
		
		private string _MaNV;
		
		private EntitySet<Xe> _Xes;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCXChanging(string value);
    partial void OnMaCXChanged();
    partial void OnDiemDiChanging(string value);
    partial void OnDiemDiChanged();
    partial void OnDiemDenChanging(string value);
    partial void OnDiemDenChanged();
    partial void OnNgayDiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDiChanged();
    partial void OnGiaVeChanging(System.Nullable<decimal> value);
    partial void OnGiaVeChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    #endregion
		
		public ChuyenXe()
		{
			this._Xes = new EntitySet<Xe>(new Action<Xe>(this.attach_Xes), new Action<Xe>(this.detach_Xes));
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCX", DbType="NChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCX
		{
			get
			{
				return this._MaCX;
			}
			set
			{
				if ((this._MaCX != value))
				{
					this.OnMaCXChanging(value);
					this.SendPropertyChanging();
					this._MaCX = value;
					this.SendPropertyChanged("MaCX");
					this.OnMaCXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemDi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiemDi
		{
			get
			{
				return this._DiemDi;
			}
			set
			{
				if ((this._DiemDi != value))
				{
					this.OnDiemDiChanging(value);
					this.SendPropertyChanging();
					this._DiemDi = value;
					this.SendPropertyChanged("DiemDi");
					this.OnDiemDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemDen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiemDen
		{
			get
			{
				return this._DiemDen;
			}
			set
			{
				if ((this._DiemDen != value))
				{
					this.OnDiemDenChanging(value);
					this.SendPropertyChanging();
					this._DiemDen = value;
					this.SendPropertyChanged("DiemDen");
					this.OnDiemDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDi", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDi
		{
			get
			{
				return this._NgayDi;
			}
			set
			{
				if ((this._NgayDi != value))
				{
					this.OnNgayDiChanging(value);
					this.SendPropertyChanging();
					this._NgayDi = value;
					this.SendPropertyChanged("NgayDi");
					this.OnNgayDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaVe", DbType="Money")]
		public System.Nullable<decimal> GiaVe
		{
			get
			{
				return this._GiaVe;
			}
			set
			{
				if ((this._GiaVe != value))
				{
					this.OnGiaVeChanging(value);
					this.SendPropertyChanging();
					this._GiaVe = value;
					this.SendPropertyChanged("GiaVe");
					this.OnGiaVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuyenXe_Xe", Storage="_Xes", ThisKey="MaCX", OtherKey="MaCX")]
		public EntitySet<Xe> Xes
		{
			get
			{
				return this._Xes;
			}
			set
			{
				this._Xes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ChuyenXe", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.ChuyenXes.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.ChuyenXes.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Xes(Xe entity)
		{
			this.SendPropertyChanging();
			entity.ChuyenXe = this;
		}
		
		private void detach_Xes(Xe entity)
		{
			this.SendPropertyChanging();
			entity.ChuyenXe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DiaDiem")]
	public partial class DiaDiem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ThanhPho;
		
		private string _BenXe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnThanhPhoChanging(string value);
    partial void OnThanhPhoChanged();
    partial void OnBenXeChanging(string value);
    partial void OnBenXeChanged();
    #endregion
		
		public DiaDiem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhPho", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ThanhPho
		{
			get
			{
				return this._ThanhPho;
			}
			set
			{
				if ((this._ThanhPho != value))
				{
					this.OnThanhPhoChanging(value);
					this.SendPropertyChanging();
					this._ThanhPho = value;
					this.SendPropertyChanged("ThanhPho");
					this.OnThanhPhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BenXe", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BenXe
		{
			get
			{
				return this._BenXe;
			}
			set
			{
				if ((this._BenXe != value))
				{
					this.OnBenXeChanging(value);
					this.SendPropertyChanging();
					this._BenXe = value;
					this.SendPropertyChanged("BenXe");
					this.OnBenXeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang
	{
		
		private string _TenKH;
		
		private string _Sdt;
		
		private string _MaVX;
		
		public KhachHang()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this._TenKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="NChar(10)")]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this._Sdt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVX", DbType="NChar(5)")]
		public string MaVX
		{
			get
			{
				return this._MaVX;
			}
			set
			{
				if ((this._MaVX != value))
				{
					this._MaVX = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _TenNV;
		
		private string _Email;
		
		private string _CCCD;
		
		private string _ChucVu;
		
		private EntitySet<ChuyenXe> _ChuyenXes;
		
		private EntitySet<TaiKhoan> _TaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    #endregion
		
		public NhanVien()
		{
			this._ChuyenXes = new EntitySet<ChuyenXe>(new Action<ChuyenXe>(this.attach_ChuyenXes), new Action<ChuyenXe>(this.detach_ChuyenXes));
			this._TaiKhoans = new EntitySet<TaiKhoan>(new Action<TaiKhoan>(this.attach_TaiKhoans), new Action<TaiKhoan>(this.detach_TaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(50)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(30)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="NChar(12)")]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(10)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ChuyenXe", Storage="_ChuyenXes", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<ChuyenXe> ChuyenXes
		{
			get
			{
				return this._ChuyenXes;
			}
			set
			{
				this._ChuyenXes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TaiKhoan", Storage="_TaiKhoans", ThisKey="MaNV", OtherKey="MaCV")]
		public EntitySet<TaiKhoan> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChuyenXes(ChuyenXe entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_ChuyenXes(ChuyenXe entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _MaCV;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnMaCVChanging(string value);
    partial void OnMaCVChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCV", DbType="NChar(10)")]
		public string MaCV
		{
			get
			{
				return this._MaCV;
			}
			set
			{
				if ((this._MaCV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCVChanging(value);
					this.SendPropertyChanging();
					this._MaCV = value;
					this.SendPropertyChanged("MaCV");
					this.OnMaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TaiKhoan", Storage="_NhanVien", ThisKey="MaCV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._MaCV = value.MaNV;
					}
					else
					{
						this._MaCV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VeXe")]
	public partial class VeXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaVX;
		
		private string _SoGheNgoi;
		
		private System.Nullable<System.DateTime> _NgayDatVe;
		
		private string _MaXe;
		
		private EntityRef<Xe> _Xe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaVXChanging(string value);
    partial void OnMaVXChanged();
    partial void OnSoGheNgoiChanging(string value);
    partial void OnSoGheNgoiChanged();
    partial void OnNgayDatVeChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDatVeChanged();
    partial void OnMaXeChanging(string value);
    partial void OnMaXeChanged();
    #endregion
		
		public VeXe()
		{
			this._Xe = default(EntityRef<Xe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVX", DbType="NChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaVX
		{
			get
			{
				return this._MaVX;
			}
			set
			{
				if ((this._MaVX != value))
				{
					this.OnMaVXChanging(value);
					this.SendPropertyChanging();
					this._MaVX = value;
					this.SendPropertyChanged("MaVX");
					this.OnMaVXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGheNgoi", DbType="NChar(5)")]
		public string SoGheNgoi
		{
			get
			{
				return this._SoGheNgoi;
			}
			set
			{
				if ((this._SoGheNgoi != value))
				{
					this.OnSoGheNgoiChanging(value);
					this.SendPropertyChanging();
					this._SoGheNgoi = value;
					this.SendPropertyChanged("SoGheNgoi");
					this.OnSoGheNgoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDatVe", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDatVe
		{
			get
			{
				return this._NgayDatVe;
			}
			set
			{
				if ((this._NgayDatVe != value))
				{
					this.OnNgayDatVeChanging(value);
					this.SendPropertyChanging();
					this._NgayDatVe = value;
					this.SendPropertyChanged("NgayDatVe");
					this.OnNgayDatVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaXe", DbType="NChar(5)")]
		public string MaXe
		{
			get
			{
				return this._MaXe;
			}
			set
			{
				if ((this._MaXe != value))
				{
					if (this._Xe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaXeChanging(value);
					this.SendPropertyChanging();
					this._MaXe = value;
					this.SendPropertyChanged("MaXe");
					this.OnMaXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_VeXe", Storage="_Xe", ThisKey="MaXe", OtherKey="MaXe", IsForeignKey=true)]
		public Xe Xe
		{
			get
			{
				return this._Xe.Entity;
			}
			set
			{
				Xe previousValue = this._Xe.Entity;
				if (((previousValue != value) 
							|| (this._Xe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Xe.Entity = null;
						previousValue.VeXes.Remove(this);
					}
					this._Xe.Entity = value;
					if ((value != null))
					{
						value.VeXes.Add(this);
						this._MaXe = value.MaXe;
					}
					else
					{
						this._MaXe = default(string);
					}
					this.SendPropertyChanged("Xe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Xe")]
	public partial class Xe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaXe;
		
		private string _Tentx;
		
		private string _BienSX;
		
		private System.Nullable<int> _SoGhe;
		
		private System.Nullable<int> _SoGheDaDat;
		
		private string _TinhTrang;
		
		private System.Nullable<System.DateTime> _GioKhoiHanh;
		
		private string _MaCX;
		
		private EntitySet<VeXe> _VeXes;
		
		private EntityRef<ChuyenXe> _ChuyenXe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaXeChanging(string value);
    partial void OnMaXeChanged();
    partial void OnTentxChanging(string value);
    partial void OnTentxChanged();
    partial void OnBienSXChanging(string value);
    partial void OnBienSXChanged();
    partial void OnSoGheChanging(System.Nullable<int> value);
    partial void OnSoGheChanged();
    partial void OnSoGheDaDatChanging(System.Nullable<int> value);
    partial void OnSoGheDaDatChanged();
    partial void OnTinhTrangChanging(string value);
    partial void OnTinhTrangChanged();
    partial void OnGioKhoiHanhChanging(System.Nullable<System.DateTime> value);
    partial void OnGioKhoiHanhChanged();
    partial void OnMaCXChanging(string value);
    partial void OnMaCXChanged();
    #endregion
		
		public Xe()
		{
			this._VeXes = new EntitySet<VeXe>(new Action<VeXe>(this.attach_VeXes), new Action<VeXe>(this.detach_VeXes));
			this._ChuyenXe = default(EntityRef<ChuyenXe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaXe", DbType="NChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaXe
		{
			get
			{
				return this._MaXe;
			}
			set
			{
				if ((this._MaXe != value))
				{
					this.OnMaXeChanging(value);
					this.SendPropertyChanging();
					this._MaXe = value;
					this.SendPropertyChanged("MaXe");
					this.OnMaXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tentx", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tentx
		{
			get
			{
				return this._Tentx;
			}
			set
			{
				if ((this._Tentx != value))
				{
					this.OnTentxChanging(value);
					this.SendPropertyChanging();
					this._Tentx = value;
					this.SendPropertyChanged("Tentx");
					this.OnTentxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BienSX", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BienSX
		{
			get
			{
				return this._BienSX;
			}
			set
			{
				if ((this._BienSX != value))
				{
					this.OnBienSXChanging(value);
					this.SendPropertyChanging();
					this._BienSX = value;
					this.SendPropertyChanged("BienSX");
					this.OnBienSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGhe", DbType="Int")]
		public System.Nullable<int> SoGhe
		{
			get
			{
				return this._SoGhe;
			}
			set
			{
				if ((this._SoGhe != value))
				{
					this.OnSoGheChanging(value);
					this.SendPropertyChanging();
					this._SoGhe = value;
					this.SendPropertyChanged("SoGhe");
					this.OnSoGheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGheDaDat", DbType="Int")]
		public System.Nullable<int> SoGheDaDat
		{
			get
			{
				return this._SoGheDaDat;
			}
			set
			{
				if ((this._SoGheDaDat != value))
				{
					this.OnSoGheDaDatChanging(value);
					this.SendPropertyChanging();
					this._SoGheDaDat = value;
					this.SendPropertyChanged("SoGheDaDat");
					this.OnSoGheDaDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="NVarChar(20)")]
		public string TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioKhoiHanh", DbType="DateTime")]
		public System.Nullable<System.DateTime> GioKhoiHanh
		{
			get
			{
				return this._GioKhoiHanh;
			}
			set
			{
				if ((this._GioKhoiHanh != value))
				{
					this.OnGioKhoiHanhChanging(value);
					this.SendPropertyChanging();
					this._GioKhoiHanh = value;
					this.SendPropertyChanged("GioKhoiHanh");
					this.OnGioKhoiHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCX", DbType="NChar(5)")]
		public string MaCX
		{
			get
			{
				return this._MaCX;
			}
			set
			{
				if ((this._MaCX != value))
				{
					if (this._ChuyenXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCXChanging(value);
					this.SendPropertyChanging();
					this._MaCX = value;
					this.SendPropertyChanged("MaCX");
					this.OnMaCXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_VeXe", Storage="_VeXes", ThisKey="MaXe", OtherKey="MaXe")]
		public EntitySet<VeXe> VeXes
		{
			get
			{
				return this._VeXes;
			}
			set
			{
				this._VeXes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuyenXe_Xe", Storage="_ChuyenXe", ThisKey="MaCX", OtherKey="MaCX", IsForeignKey=true)]
		public ChuyenXe ChuyenXe
		{
			get
			{
				return this._ChuyenXe.Entity;
			}
			set
			{
				ChuyenXe previousValue = this._ChuyenXe.Entity;
				if (((previousValue != value) 
							|| (this._ChuyenXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChuyenXe.Entity = null;
						previousValue.Xes.Remove(this);
					}
					this._ChuyenXe.Entity = value;
					if ((value != null))
					{
						value.Xes.Add(this);
						this._MaCX = value.MaCX;
					}
					else
					{
						this._MaCX = default(string);
					}
					this.SendPropertyChanged("ChuyenXe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VeXes(VeXe entity)
		{
			this.SendPropertyChanging();
			entity.Xe = this;
		}
		
		private void detach_VeXes(VeXe entity)
		{
			this.SendPropertyChanging();
			entity.Xe = null;
		}
	}
}
#pragma warning restore 1591
